### ISSUE TITLE
Commits that have no effect still get added to the transaction graph

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#106]
This may not be a problem at all, but I can see wanting to have a smart `commit` that detects this case and just does nothing to the transaction graph.

**Comment by agentm** [comment]
This is true and is handy for testing, but I can understand why it might cause some confusion. Do you think that commit should return an error or should just silently do nothing? By the way, git allows committing empty commits to the graph but it requires an extra flag.

**Comment by 3noch** [comment]
My thought is that avoiding unnecessary commits *could* be faster. But most importantly it avoids the need to do rebasing or merging when there are multiple writers.

**Comment by agentm** [comment]
Fixed in 261654cb2ff460b06f3d68c0da3d3600f3996abc.

I also put in the foundations for the equivalent to SQL's RETURNING, but I'll open a separate ticket to complete that.

**Comment by 3noch** [comment]
Fantastic! It looks like this is a very deep detection. Does it also detect updates and deletions that have no effect?

**Comment by agentm** [comment]
Indeed it does. See [the test](https://github.com/agentm/project-m36/blob/master/test/TutorialD/Interpreter.hs#L402) for examples.

I am of mixed opinion on this "feature" because the client cannot know whether or not an update actually changed the database until a commit is attempted, but that should be resolved by allowing for per-update metadata to be returned. Alternatively, I should likely add a commit flag to allow for empty commits (just like ```git```).

**Comment by 3noch** [comment]
What are your concerns about clients not knowing whether they actually changed the database?

**Comment by agentm** [comment]
Consider, if a client issues:

```
update suppliers where sname="Steve" (city:="Boston");
:commit
```
and there is no "Steve", then the client receives an error.

This behavior is not orthogonal to inserts or deletes which may do nothing but don't throw an error. Should there be a variant of insert/update/delete which throw a similar error, too? I am doubtful, but am willing to be convinced otherwise.

At the very least, I would like to offer an invocation of ```commit``` which does not throw the error. 

Or perhaps the command should be inverted:

* normal ```:commit``` never throws the ```EmptyCommitError```
* ```:commit nonempty``` (or something like that) would throw the error when no real update has been made

Obviously, the syntax only matters from the TutorialD standpoint- the DSL would require the flag either way. What do you think?

**Comment by 3noch** [comment]
I see. I didn't realize that empty commits threw an error. For some reason, intuitively (not based on some deep theoretically understanding), I feel that not throwing is the right default. The fact that a commit had no effect seems like an implementation detail that most clients won't care about.

**Comment by agentm** [comment]
I was blind to it before, but since I re-read the issue, I suppose there is a third option: ignore the commit altogether. I hadn't considered this before. Do we really need three different forms of commit? I need to think about this some more.

I chose the error option simply because that is git's default, but that need not necessarily be a reasonable database default. I am also wary of a "commit" which does nothing- but that could merely be legacy thinking.

**Comment by agentm** [comment]
In any case, I'll add the necessary flag to the Commit value and we can hash out a default later.

**Comment by 3noch** [comment]
Actually ignoring the commit altogether is what I was doing in my code. That makes the most sense to me since you're not actually affecting the transaction graph in any meaningful way.

**Comment by 3noch** [comment]
That would also be the same intuition as git, where making no changes *usually* means that you just don't make a commit at all.

**Comment by agentm** [comment]
Hah- well I interpreted git's default behavior differently:

```bash
$ git commit 
# On branch master
nothing to commit (working directory clean)
$ echo $?
1
```

This appears to be an error but I can understand why it looks like it does nothing.

**Comment by 3noch** [comment]
Good point. In that case another option is to expose the `isDirty` flag (i.e. `git status`) and allow the user code to conditionally commit. That's how I'd do it in git. And that's how I'm doing it in my code now (albeit with a much cruder version of `isDirty` that what you now provide).

**Comment by agentm** [comment]
I have mixed feelings about this feature due to how it will interact with the increased laziness implementation to support constant-time commits. Here is the problem: when transactions are not fully evaluated by commit-time, it's impossible to statically determine if the evaluation (or future evaluation) will result in no change. Determining if the expression will result in no change is essential in rejecting empty commits, but if we cannot determine that at commit-time, then we cannot return the ``EmptyCommitError```.

I think this reasoning has some practical consequences:

* the default commit style must allow empty commits to allow for maximum laziness
* if the user wants to reject empty commits, the expression must be fully evaluated before commit

I think the second point would probably not be obvious to the user, so I would rather remove the empty commit detection because it creates additional error states which may not be obvious to the user.

**Comment by 3noch** [comment]
Hmm, why remove the detection? I cannot imagine a single use-case for wanting to get an error there. I'd always want empty commits to move on silently.

**Comment by 3noch** [comment]
In my mind empty commits are "fastforward merges" in `git`. In `git`, if running `git status` says there is nothing to commit, then I don't commit. Since this database doesn't have `git status` then it makes sense to just not create an error on empty-commits.

**Comment by agentm** [comment]
Empty commits can also arise from commands which end up performing no change. This is especially likely with the new "automerge-to-head" facility. If two competing clients perform the same update such as:

```
update x where user="Bob" (status:=10)
```
while using the automerge, then both clients will succeed but one commit will be empty. It wouldn't make sense to generate an error for this case. This becomes more complicated once lazy commits are implemented- we cannot determine if a commit is empty until after we evaluate the expression, but lazy commits deliberately avoid evaluation.

**Comment by agentm** [comment]
I am thinking that the empty commit detection will merely become a server-side optimization and can't be reliably exposed to users (as an option) without leaking implementation details.

**Comment by 3noch** [comment]
I'm perfectly happy with that! ;)

**Comment by 3noch** [comment]
You could witness the optimization by looking at the transaction graph after a commit, but that's all.
