### ISSUE TITLE
How to extract and use the result of executeRelationalExpr? 

### ISSUE THREAD

**Issue by zanzix** [agentm/project-m36#115]
I'm having a bit of a trouble with figuring out some of the functionality at the interface between tutd and Haskell. 

My use-case is building servers, and I want to connect the ProjectM36 client to a RESTful API, but I couldn't find documentation on how to turn the result of executeRelationalExpr back into a haskell record, or how to use the result in other relational expressions.

Lets say I have two Haskell datatypes:

```
data BlogPost = BlogPost
  { postId   :: Int
  , content  :: String }

data User = User
  { userId   :: Int
  , name     :: String }

```

And they both have a corresponding representation in tutd, which also has a relationship that tracks which BlogPost belongs to which User. 

Lets say that I want to write a haskell function which gives me all blog posts for a given userId. 

```
postsForUserId :: Int -> [BlogPost] 
postsForUserId = undefined

```

My issue is that I'm not sure how to turn the result of "rel <- executeRelationalExpr" into [BlogPost]. (To be honest, without haddock documentation I'm not entirely sure what the structure of rel even is). 

I'd appreciate if you could show me how to do that! 

Additionally, you can probably do the whole thing in a single use of executeRelationalExpr, but lets say that we're dealing with a very complicated expression and it needs to be split into two - could you also write postsForUserId' which shows how to use the result of executeRelationalExpr as input for another executeRelationalExpr? 

ie something along the lines of

```
postsForUserId' :: Int -> [BlogPost] 
postsForUserId' = 
  postIds <- executeRelationalExpr expr1 
  -- turn postIds into another relational expression, expr2 
  blogPosts <- executeRelationalExpr epxr2 ...

```  

Thanks in advance, and thanks again for the great library! I can't wait to get to the more advanced functionality.

**Comment by agentm** [comment]
Hi @zanzix- thanks for trying Project:M36!

Project:M36 does offer an ```Atomable``` typeclass to marshal values between Haskell and Project:M36 which is derivable for data types implementing ```Generic```. For a simple example, take a look at [hair.hs](https://github.com/agentm/project-m36/blob/master/examples/hair.hs). But, ```Atomable``` types are better-suited for "fundamental" types like colors. For record types, I intend to implement #110 which will marshal Haskell record types to tuples and back. Unfortunately, that doesn't exist yet, but it's possible with some manual steps.

```
postsForUserId :: Int -> IO (Either RelationalError [BlogPost])
postsForUserId userId = do
  let predicate = AttributeEqualityPredicate "userId" userId
  eResult <- executeRelationalExpr sess conn (Restrict predicate (RelationVariable "BlogPost" ())
  case eResult of
    Left err -> pure (Left err)
    Right postsRel -> do
      let posts = relFold (\tup accum -> let Left pid = atomForAttributeName "postId" tup
                                                                  Left text = atomForAttributeName "content" tup  in
accum ++ BlogPost {postId = pid , content= text}) [] postsRel
      pure (Right posts)
```
(Warning: untested and some error handling elided.)

There is some boilerplate above which I hope the ```Tupleable``` typeclass and the new simple API suggested by @3noch can reduce. So, we're not quite on-par with the ease-of-use of acid-state, but we're close. Note that we run in IO because the database can be remote.

For the second function, just create the proper ```Atom``` type on which to restrict, for example:

```
executeRelationalExpr sess conn (Restrict (AttributeEqualityPredicate "postId" (IntAtom realIntFromPreviousRequest)) (RelationVariable "BlogPost" ())
```

I'll add a ticket to generate and host haddock documentation somewhere- I certainly understand its usefulness and Haskellers expect it to be available even if the text explanations are incomplete right now.

**Comment by zanzix** [comment]
Thanks a lot, this explains it well!

Looking forward to seeing the haddoc docs. I think uploading to hackage will be indeed the easiest way.

**Comment by agentm** [comment]
Hi @zanzix, the project-m36 package is now available on hackage. I recommend starting with [ProjectM36.Client](http://hackage.haskell.org/package/project-m36-0.1/docs/ProjectM36-Client.html). 

Thanks for your comments which made me realize the importance of haddock docs!

**Comment by zanzix** [comment]
Glad to help! :)  And thanks for putting the docs online, it's so much easier to figure things out now!
