### ISSUE TITLE
Improve binary format error messages

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#133]
When upgrading recently I forgot to delete my old database. When using the new version I got an error like `Data.Binary.Get.runGet not enough bytes`. Is there an easy way to proactively check for data format version mismatches? At the least this type of error could be caught and reworded?

**Comment by agentm** [comment]
Indeed! The whole read/write graph system is peppered with ```error``` invocations due to lazy programming. My excuse is that using ```Binary``` was a short-term solution until we cook up a relation-specific format (including referencing previous transactions). In the meantime, I should definitely update the format version.
