### ISSUE TITLE
Update stack.yaml to LTS 9

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#137]
Since #136, Project-M36 no longer supports pre-LTS-9.

**Comment by agentm** [comment]
Uh, what a hassle. distributed-process 0.6.6 wants to pull in syb 0.7 which stack doesn't like and upgrading to a later version of distributed-process won't work because the distributed-process ecosystem modules haven't yet been updated (version bounds needs to be bumped). That's frustrating, but @3noch has some pull requests pending on those packages.

Until some new releases of d-p-extras, -async, and -client-server are released, stack builds are broken :/

**Comment by 3noch** [comment]
Yuck. You *could* pull in my forks of those processes if you want to get it working for now.

**Comment by agentm** [comment]
Luckily, I use ol' cabal sandboxes for development, so it doesn't bother me, but it would be nice if distributed-process would release their packages in lockstep.

**Comment by 3noch** [comment]
@agentm Also I believe stack has an `--allow-newer` flag you can use somehow. But if it isn't bothering you then there's little reason to fix it urgently.

**Comment by agentm** [comment]
We're dropping support for GHC 8.0.2.
