### ISSUE TITLE
Consider using proxy types instead of undefined in some places

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#144]
As I've been working more with `Tupleable`, etc, I've realized some differences (and potential pitfalls) of using `undefined :: a` instead of `Proxy @a` (or `Proxy :: Proxy a` for GHC < 8):

Unlike `Proxy`, `undefined` masquerades as a *value* of type `a`. If your API doesn't touch this value, then, of course,  you're fine. However, if you have any available constraints on `a`, then all of those type-class methods will work. For example, `Tupleable a` has `NFData a` and `Binary a`, which means the implementation of `Tupleable` can use methods of these classes, possibly inadvertently.

The benefit of a proxy type here is that you simply can't implement any of this incorrectly, because you never actually get a value of type `a`.

```haskell
class Tupleable a where
  toAttributes :: proxy a -> [Attribute]
  ...

-- call-sight
toAttributes (Proxy @MyRecord)
```

It helps to know that you can make a type variable available in the body of a function using `-XScopedTypeVariables` and `forall`.

**Comment by 3noch** [comment]
I thought I'd bring this up now as the API is still young.

**Comment by agentm** [comment]
I took a stab at this, but there is actually one case where the the value is essential for constructing the atom type: relations as atoms. Since relations have a type, that type is reflected back into the AtomType. Relations carry their types around as a set of attributes.

So, in order to replace the type-based APIs with proxies, we would have to drop support for relations as Atomable. I don't necessarily object to this if it improves the API, but it seems rather arbitrary. What do you think?

**Comment by cumber** [comment]
I've just started exploring project-m36, and was a bit irked by the `undefined` usage too.

I think there is a problem with the API of relations being Atomable.

For everything other than relations you have `toAtomType` being essentially a type-driven function, which is why you usually pass `undefined`. You don't want the `AtomType` corresponding to the *value* 12.0, but to the *type* `Double`. Indeed if the `AtomType` *did* depend on the value, then `toAtomType` wouldn't be particularly useful, because the expected pattern is that you can call it once before you have any values and get an `AtomType` that's useful for all values of that type.

But relations are dynamically typed, so there's no mapping from the Haskell type system to the database type system. So you have to use the `Atomable` functions with a completely different pattern; rather than the Haskell type determining the `AtomType`, you need to construct a `Relation` to indicate what the desired `AtomType` is (where I suppose an empty relation can stand in as a "type object").

It feels a bit fragile that for most types you're expected to pass `undefined` (and often won't have a sensible value to pass even if you didn't want to use undefined), but for `Relation` you **must not** pass undefined. It makes it difficult to write client code polymorphic in an `Atomable` type; how do you know which usage pattern you're supposed to be following?

To me it does hint that the way relations are "atomable" isn't really the same as the way that everything else is "atomable". My suggestion would be to to declare that `Atomable` is the class of Haskell *types* that uniquely determine an `AtomType`, and therefore `Relation` shouldn't have an instance. You could either have another class for "dynamically-typed" Haskell types (where you need more information than the type to know what the `AtomType` is; could be theoretically useful for other things like aeson?), or just standalone functions for embedding relations as atoms.

I don't really have enough usage experience yet to know whether the loss of `Atomable Relation` would be a pain though; it would mean the polymorphic instances like `Atomable a => Atomable (Maybe a)`  wouldn't apply to `Relation`, for example. Do things like `Maybe Relation`, `[Relation]`, etc, arise naturally in practice?

Although I just had a look at the code for the polymorphic instances, and it looks like they all pass `undefined` to the underlying instance, which means as it stands they in fact wouldn't work with `Relation`! (That's what I was talking about when I referred to it being difficult to write `Atomable`-polymorphic code earlier)

**Comment by cumber** [comment]
A much more radical alternative would be to use a `HList`-like approach to make the Haskell type of relations reflect their database type. I imagine that would be a fairly huge overhaul though!
