### ISSUE TITLE
attribute names of foreign key condition must have the same name

### ISSUE THREAD

**Issue by testexplode** [agentm/project-m36#181]
The following commands in tuts give the wrong error:

```
authors := relation{tuple{name "agentM"}}
kernel_req := relation{tuple{author "moin", no 0}}
foreign key author_exits kernel_req{author} in authors{name}
ERR: AttributeNamesMismatchError (fromList ["author","name"])
```
I would expect that the condition is not accepted because of the missing author, not because of the wrong attribute names.

A test with the the same attribute names in both relations gives the correct error.

I use the latest version in the branch support_ghc_8.2

**Comment by agentm** [comment]
@testexplode brought up this issue on our IRC channel and I asked him to open a ticket. After I mistakenly assumed that this is bug, I have an explanation as to why this behavior is expected.

In the case of a single attribute foreign key constraint, the two attributes must obviously (unambiguously) be the attributes in question to match so the names of the attributes are largely irrelevant. However, if the constraint refers to two-or-more attributes in both sides of the constraint, then, because attributes in a relation do not a specific ordering, then matching attributes for a potential union is ambiguous. For example, for foreign key constraint "x{a,b} in y{c,d}" it is not clear whether "a" maps to "c" or "d". Furthermore, the types of a,b,c, an d could be identical, so guessing based on the types would fail as well.

In this case, it makes sense that the relational algebra would require that the two sides of the constraint be unionable, that is, of the same type/attributes which includes the names of the attributes.

Still, this issue caught me and a user off-guard, so I will improve the documentation and the returned error message.

**Comment by agentm** [comment]
I cherry-picked the better error message patch to the "support_GHC_8.2" branch.
