### ISSUE TITLE
What is the purpose of ``TypeConstructorMapping`` in ``csvAsRelation``

### ISSUE THREAD

**Issue by kozross** [agentm/project-m36#252]
This function is a bit unclear to me, but this argument in particular is confusing. What does it do, and how would I provide one correctly?

**Comment by agentm** [comment]
The `TypeConstructorMapping` holds onto all the type constructor definitions along with related data constructors. This is necessary in decoding CSV because we support writing CSV files with user-defined algebraic data types, so we have to be able to read them back.

Typically, this mapping is maintained by the database and passed around as necessary, but you can get a bootstrapped version in [`DataTypes/Basic.hs`](https://github.com/agentm/project-m36/blob/master/src/lib/ProjectM36/DataTypes/Basic.hs#L11)

**Comment by kozross** [comment]
How would I define one, supposing I had three attributes, one being a ``Text``, another an ``Int``, and another a user-defined type ``Foo``?

**Comment by agentm** [comment]
Take a look at the [primitive data types](https://github.com/agentm/project-m36/blob/master/src/lib/ProjectM36/DataTypes/Primitive.hs) as well as the [non-empty list type](https://github.com/agentm/project-m36/blob/master/src/lib/ProjectM36/DataTypes/NonEmptyList.hs) for examples.

**Comment by agentm** [comment]
Please reopen this ticket if you need further assistance.
