### ISSUE TITLE
Pull persistent driver into separate package

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#79]
Would it make sense to separate the persistent driver into a separate package? It seems like a useless dependency to anyone who doesn't plan on using it.

**Comment by agentm** [comment]
That's not a bad idea. I suspect no one is using it regardless.

**Comment by agentm** [comment]
In the end, I chose to simply delete the driver and its dependencies. If there any interest in such a driver later, it can be resurrected.

**Comment by agentm** [comment]
I was hoping that removing the stale persistent driver would allow us to build on both stackage LTS version for GHC 7.10 and GHC 8.0.1, but the LTS version include different megaparsec versions. 

Would there be any resistance to requiring GHC 8 for stack builds? I imagine that it might be too soon to require GHC 8 for stack, but I can't be certain. 

From my perspective, it would be easier to maintain since I would be able to drop one platform.

**Comment by 3noch** [comment]
Considering Project:M36 is young and doesn't have much of a following yet, I wouldn't consider it too restrictive to drop support for GHC 7. By the time Project:M36 has a decent following, GHC 7.10 will be approaching legacy. (GHC 8.2 is already on the horizon.)

**Comment by agentm** [comment]
Sure, it was deleted in 4ed335ebd0b5e87cc5a649a0d5d0dc239f82a9f8, so 15521e5f634f9ccfa79c26554c64e34b153c0e46 still has it under `src/persistent/`. I do recall it doesn't work with the latest version of persistent, though, because some type families were split apart, so it will need some polish, but it should mostly be code rearranging.

Also, once I finally find time to finish off your dataframes merge request (sorry!), that will add a lot of missing functionality which the persistent driver requires such as sorting.

In any case, feel free to spin off the project-m36 persistent driver into a separate project; either as a different github project or a cabal project (which supports multiple libraries per repo).

**Comment by YuMingLiao** [comment]
Thanks for the heads-up. I'll see what I can do. And don't worry about request. I am not in a hurry. I just have some spare time to learn haskell and I am glad to start from this very-interesting project. Thanks for the help! Good day!

**Comment by YuMingLiao** [comment]
Hi, @agentm, I have done some polish. [persistent-project-m36](https://github.com/YuMingLiao/persistent-project-m36) can insert, delete, selectList without selectOpts now. 

However, it seems I can't store a `Maybe Int` through Persistent due to unsupported PersistentValue. (ProjectM36 supports ADT, which is really awosome!)

Has anyone use yesod+project-m36? maybe with yesod-auth?

**Comment by YuMingLiao** [comment]
I see. It looks like project-m36 can be more flexible without the intermediate layer. I'll look into if I can have a yesod-project-m36 like yesod-persistent. Thanks for the support!
